kind: Deployment
apiVersion: apps/v1
metadata:
  name: expense-app-deployment
  namespace: expense-app
  labels:
    app: expense-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-app
  template:
     metadata:
       labels:
        app: expense-app
     spec:
       containers:
       - name: expense-app
         image: prakashgautam1998/expense-app
         ports:
         - containerPort: 8080
         env:
         - name: SPRING_DATASOURCE_USERNAME
           value: "root"
         - name: SPRING_DATASOURCE_URL 
           value: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
         - name: SPRING_DATASOURCE_PASSWORD
           value: "Test@123"
          

